[package]
name = "es4forensics"
version = "0.1.0"
edition = "2021"
description = "Import several timelines into elasticsearch"
homepage = "https://www.github.com/janstarke/es4forensics"
repository = "https://www.github.com/janstarke/es4forensics"
license = "GPL-3.0"


[dependencies]
# requires libssl-dev
elasticsearch = "8.4.0-alpha.1"
duplicate = "0.4"
serde = "~1"
serde_json = "~1"
anyhow = "1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
chrono-tz = "0.6"
log = "0.4"
sha2 = "0.10"
base64 = "0.13"

bodyfile = "0.1"
