[package]
name = "elastic4forensics"
version = "0.1.0"
edition = "2021"

[dependencies]
# requires libssl-dev
elasticsearch = "8.4.0-alpha.1"
duplicate = "0.4"
serde = "~1"
serde_json = "~1"
anyhow = "1"
futures = "0.3"
tokio = { version = "*", features = ["full"] }
chrono = "0.4"
chrono-tz = "0.6"

bodyfile = "0.1"